# Generated by Django 4.0.6 on 2022-07-23 23:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farlhefe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='Duration (ms)'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='quantity',
            field=models.PositiveSmallIntegerField(verbose_name='Quantity (g)'),
        ),
    ]
